name: "build-simlar-ios"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: cocoapods
      run: pod install
    - name: build
      run:  xcodebuild clean build -workspace Simlar.xcworkspace/ -scheme Simlar -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 12'
