name: "simlar-ios-ci"
on:
  schedule:
    - cron: '0 3 * * *'
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 30
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: cocoapods
      run: pod install
    - name: build
      run:  xcodebuild clean build -workspace Simlar.xcworkspace/ -scheme Simlar -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 16'
